### PR TITLE
ProxyHelper2

### PR DESCRIPTION
**Pull request by hoodoer**
A module that forces TCP traffic on specific ports (configurable) from client devices to Burp Suite Proxy. This is incredibly handy for testing mobile applications that refuse to honor proxy settings on the device. 

This is a re-implementation of the original ProxyHelper by @_kc57 to work on the new module system. 

Original module blog:
https://trustedsec.com/blog/introducing-proxy-helper-a-new-wifi-pineapple-module

Blog post for ProxyHelper2 will be published on TrustedSec.com soon.

### CODE REVIEW

**Comment by dragorn** [comment]
Looks good - will look at it more fully next week and get it merged, thanks!

**Comment by hoodoer** [comment]
Thanks dragorn, appreciate the assistance. Let me know if you have any questions or need any changes made.

**Comment by hoodoer** [comment]
Any chance this is going to get pulled in this week?

**Comment by dragorn** [comment]
Yeah; it's on the list, several of us were at ShmooCon so lagging a bit.

**Comment by hoodoer** [comment]
Much appreciated! Wish I had know you were there so I coulda gotta you a beer in thanks :)

**Pull request merged**
